version: "3.9"

services:
  backend:
    build:
      context: ./tricity-be
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./tricity-be:/app
    networks:
      - tricity-network
    environment:
      - PORT=${BACKEND_PORT}
      - MONGODB_URI=mongodb://mongo:27017/tricity
      - REDIS_URL=redis://redis:6379
      - COOKIE_SECRET=${COOKIE_SECRET}
    depends_on:
      - mongo
      - redis
    env_file:
      - .env

  frontend:
    build:
      context: ./tricity-fe
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./tricity-fe:/app
      - /app/node_modules
    networks:
      - tricity-network
    depends_on:
      - backend
    environment:
      - PORT=${FRONTEND_PORT}
      - APP_BACKEND_URL=http://${BACKEND_HOST}:${BACKEND_PORT}
    env_file:
      - .env

  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tricity-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - tricity-network

volumes:
  mongo-data:

networks:
  tricity-network:
    driver: bridge
